### ISSUE TITLE
Can you post feature-sample expression matrix on github ?

### ISSUE THREAD

**Issue by daydream-boost** [hamidghaedi/scRNA_seq-analysis#2]
Hi,

Thank you for sharing you code about scRNA-seq analysis.  Can you post feature-sample expression matrix on github? So we can not download the big fastq files and run cellranger again which will cost too much time.

Thanks.

**Comment by hamidghaedi** [comment]
@daydream-boost  thank you for your interest in my code.  You may find the `cellranger count` outputs using the following link:
https://figshare.com/articles/dataset/filtered_zip/23834670

**Comment by hamidghaedi** [comment]
Link to the dataset provided.
